<a href="https://colab.research.google.com/github/F1ameX/2025-ODS-NLP/blob/main/practice_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Install and Import Libraries

In [54]:
!pip install --quiet catboost
!pip install --quiet gensim

In [55]:
import os
import re
import pandas as pd

from catboost import Pool, CatBoostClassifier

## Read Data

In [56]:
path = '/content/drive/MyDrive/ods-nlp_src/practice_2/'
train_data = pd.read_csv(os.path.join(path, 'train.csv'))
test_data = pd.read_csv(os.path.join(path, 'test.csv'))
print(f'Number of rows and columns in the train data set: {train_data.shape}')
print(f'Number of rows and columns in the test data set: {test_data.shape}')
train_data.head()

Number of rows and columns in the train data set: (48665, 2)
Number of rows and columns in the test data set: (12167, 2)

   rate                                               text
0     4  Очень понравилось. Были в начале марта  с соба...
1     5  В целом магазин устраивает.\nАссортимент позво...
2     5  Очень хорошо что открылась 5 ка, теперь не над...
3     3  Пятёрочка громко объявила о том как она заботи...
4     3  Тесно, вечная сутолока, между рядами трудно ра...

In [57]:
train_data.groupby('rate').describe()

       text
      count unique                top freq
rate
1      4138   4130             Грязно    3
2      2410   2407  Отстойный магазин    2
3      6126   6070          Нормально    7
4      9922   9763               Норм   14
5     26069  24804    Хороший магазин  107

## Preparing the data and creating Catboost model

In [58]:
train_data['text'].sample(7)

45535    Очень вежливые продавцы и санитарка. Ходишь ка...
38130    Всё нормально. Хорошее обслуживание, вежливый ...
14735                               Самый лучший персонал)
11439    Хороший,  чистый магазин.  Между рядами достат...
35069                                           Все хорошо
41332    Ассортимент маленький, но это болезнь почти вс...
25858    После обновления магазина, всё стало лучше. Ра...
Name: text, dtype: object

In [59]:
train_data['text'] = train_data['text'].str.lower()
train_data['text'] = train_data['text'].apply(lambda x: re.sub(r'[^\w\s]', '', x))

In [60]:
train_data['text'].sample(7)

36413    иногда работает одна касса на весь магазинстал...
42568                                   магазин приличный
16313     хороший магазин и персонал вежливый и отзывчивый
32543    магазин чистый товар аккуратно выставлен на по...
7692     хороший магазин большой ассортимент 4 кассы к ...
10606    вежливый персонал обслуживание хорошее подскаж...
9733     если честно скудный выбор товаров еда есть в п...
Name: text, dtype: object

In [64]:
X_train = train_data['text']
y_train = train_data['rate']

X_test = test_data['text']


model = CatBoostClassifier(
    iterations = 150,
    depth = 5,
    random_seed = 52
)

model.fit(
    X_train,
    y_train,
    text_features = [0],
    verbose=True
)

Learning rate set to 0.479263
0:	learn: 1.1007137	total: 5s	remaining: 12m 25s
1:	learn: 1.0168544	total: 8.53s	remaining: 10m 30s
2:	learn: 0.9655813	total: 12.2s	remaining: 9m 56s
3:	learn: 0.9423265	total: 16.9s	remaining: 10m 18s
4:	learn: 0.9326649	total: 20.8s	remaining: 10m 2s
5:	learn: 0.9233729	total: 24.3s	remaining: 9m 43s
6:	learn: 0.9179431	total: 27.8s	remaining: 9m 28s
7:	learn: 0.9128259	total: 33s	remaining: 9m 45s
8:	learn: 0.9086044	total: 36.5s	remaining: 9m 31s
9:	learn: 0.9025016	total: 40.1s	remaining: 9m 20s
10:	learn: 0.9006064	total: 44.4s	remaining: 9m 20s
11:	learn: 0.8992378	total: 48.8s	remaining: 9m 21s
12:	learn: 0.8950451	total: 52.4s	remaining: 9m 11s
13:	learn: 0.8932517	total: 55.9s	remaining: 9m 3s
14:	learn: 0.8898222	total: 1m 1s	remaining: 9m 9s
15:	learn: 0.8884537	total: 1m 4s	remaining: 9m
16:	learn: 0.8876079	total: 1m 8s	remaining: 8m 52s
17:	learn: 0.8866073	total: 1m 12s	remaining: 8m 48s
18:	learn: 0.8850125	total: 1m 16s	remaining: 8m 49s
19:	learn: 0.8840243	total: 1m 20s	remaining: 8m 42s
20:	learn: 0.8833073	total: 1m 23s	remaining: 8m 35s
21:	learn: 0.8810997	total: 1m 28s	remaining: 8m 37s
22:	learn: 0.8791197	total: 1m 32s	remaining: 8m 31s
23:	learn: 0.8770284	total: 1m 36s	remaining: 8m 25s
24:	learn: 0.8736194	total: 1m 40s	remaining: 8m 21s
25:	learn: 0.8725014	total: 1m 45s	remaining: 8m 21s
26:	learn: 0.8704581	total: 1m 48s	remaining: 8m 15s
27:	learn: 0.8682996	total: 1m 52s	remaining: 8m 9s
28:	learn: 0.8670790	total: 1m 56s	remaining: 8m 7s
29:	learn: 0.8651941	total: 2m 1s	remaining: 8m 4s
30:	learn: 0.8640946	total: 2m 4s	remaining: 7m 57s
31:	learn: 0.8619269	total: 2m 8s	remaining: 7m 52s
32:	learn: 0.8606999	total: 2m 13s	remaining: 7m 52s
33:	learn: 0.8588934	total: 2m 16s	remaining: 7m 46s
34:	learn: 0.8577346	total: 2m 20s	remaining: 7m 41s
35:	learn: 0.8561820	total: 2m 24s	remaining: 7m 37s
36:	learn: 0.8545653	total: 2m 29s	remaining: 7m 35s
37:	learn: 0.8535966	total: 2m 32s	remaining: 7m 29s
38:	learn: 0.8522349	total: 2m 36s	remaining: 7m 24s
39:	learn: 0.8510960	total: 2m 41s	remaining: 7m 23s
40:	learn: 0.8500368	total: 2m 44s	remaining: 7m 18s
41:	learn: 0.8481122	total: 2m 48s	remaining: 7m 12s
42:	learn: 0.8471012	total: 2m 52s	remaining: 7m 8s
43:	learn: 0.8455383	total: 2m 57s	remaining: 7m 6s
44:	learn: 0.8437622	total: 3m	remaining: 7m 1s
45:	learn: 0.8426556	total: 3m 4s	remaining: 6m 56s
46:	learn: 0.8415069	total: 3m 9s	remaining: 6m 54s
47:	learn: 0.8403513	total: 3m 13s	remaining: 6m 50s
48:	learn: 0.8392878	total: 3m 16s	remaining: 6m 45s
49:	learn: 0.8383489	total: 3m 20s	remaining: 6m 40s
50:	learn: 0.8371290	total: 3m 25s	remaining: 6m 38s
51:	learn: 0.8360524	total: 3m 28s	remaining: 6m 33s
52:	learn: 0.8351114	total: 3m 32s	remaining: 6m 28s
53:	learn: 0.8340816	total: 3m 36s	remaining: 6m 25s
54:	learn: 0.8330231	total: 3m 41s	remaining: 6m 22s
55:	learn: 0.8313232	total: 3m 44s	remaining: 6m 17s
56:	learn: 0.8308015	total: 3m 48s	remaining: 6m 12s
57:	learn: 0.8295006	total: 3m 53s	remaining: 6m 10s
58:	learn: 0.8288982	total: 3m 57s	remaining: 6m 5s
59:	learn: 0.8280182	total: 4m	remaining: 6m
60:	learn: 0.8270326	total: 4m 4s	remaining: 5m 57s
61:	learn: 0.8261378	total: 4m 9s	remaining: 5m 53s
62:	learn: 0.8252060	total: 4m 12s	remaining: 5m 49s
63:	learn: 0.8244415	total: 4m 16s	remaining: 5m 44s
64:	learn: 0.8237865	total: 4m 21s	remaining: 5m 42s
65:	learn: 0.8231510	total: 4m 25s	remaining: 5m 37s
66:	learn: 0.8221349	total: 4m 28s	remaining: 5m 32s
67:	learn: 0.8211242	total: 4m 32s	remaining: 5m 28s
68:	learn: 0.8204337	total: 4m 37s	remaining: 5m 25s
69:	learn: 0.8196162	total: 4m 41s	remaining: 5m 21s
70:	learn: 0.8189766	total: 4m 44s	remaining: 5m 16s
71:	learn: 0.8184307	total: 4m 49s	remaining: 5m 13s
72:	learn: 0.8174004	total: 4m 53s	remaining: 5m 9s
73:	learn: 0.8163343	total: 4m 56s	remaining: 5m 4s
74:	learn: 0.8158091	total: 5m	remaining: 5m
75:	learn: 0.8147478	total: 5m 5s	remaining: 4m 57s
76:	learn: 0.8141009	total: 5m 9s	remaining: 4m 53s
77:	learn: 0.8134862	total: 5m 12s	remaining: 4m 48s
78:	learn: 0.8127082	total: 5m 17s	remaining: 4m 45s
79:	learn: 0.8121837	total: 5m 21s	remaining: 4m 41s
80:	learn: 0.8116523	total: 5m 24s	remaining: 4m 36s
81:	learn: 0.8108382	total: 5m 28s	remaining: 4m 32s
82:	learn: 0.8099952	total: 5m 33s	remaining: 4m 29s
83:	learn: 0.8092309	total: 5m 37s	remaining: 4m 24s
84:	learn: 0.8082077	total: 5m 40s	remaining: 4m 20s
85:	learn: 0.8076073	total: 5m 45s	remaining: 4m 16s
86:	learn: 0.8068568	total: 5m 49s	remaining: 4m 13s
87:	learn: 0.8059820	total: 5m 53s	remaining: 4m 8s
88:	learn: 0.8053805	total: 5m 56s	remaining: 4m 4s
89:	learn: 0.8046409	total: 6m 1s	remaining: 4m 1s
90:	learn: 0.8037904	total: 6m 5s	remaining: 3m 56s
91:	learn: 0.8033821	total: 6m 8s	remaining: 3m 52s
92:	learn: 0.8029331	total: 6m 13s	remaining: 3m 48s
93:	learn: 0.8024147	total: 6m 17s	remaining: 3m 44s
94:	learn: 0.8019414	total: 6m 21s	remaining: 3m 40s
95:	learn: 0.8012243	total: 6m 24s	remaining: 3m 36s
96:	learn: 0.8004920	total: 6m 29s	remaining: 3m 33s
97:	learn: 0.7996405	total: 6m 33s	remaining: 3m 28s
98:	learn: 0.7988965	total: 6m 37s	remaining: 3m 24s
99:	learn: 0.7982880	total: 6m 41s	remaining: 3m 20s
100:	learn: 0.7975521	total: 6m 46s	remaining: 3m 16s
101:	learn: 0.7964531	total: 6m 49s	remaining: 3m 12s
102:	learn: 0.7957171	total: 6m 53s	remaining: 3m 8s
103:	learn: 0.7953516	total: 6m 57s	remaining: 3m 4s
104:	learn: 0.7948162	total: 7m 1s	remaining: 3m
105:	learn: 0.7942356	total: 7m 5s	remaining: 2m 56s
106:	learn: 0.7928723	total: 7m 9s	remaining: 2m 52s
107:	learn: 0.7923175	total: 7m 14s	remaining: 2m 48s
108:	learn: 0.7915855	total: 7m 17s	remaining: 2m 44s
109:	learn: 0.7910181	total: 7m 21s	remaining: 2m 40s
110:	learn: 0.7899630	total: 7m 25s	remaining: 2m 36s
111:	learn: 0.7893549	total: 7m 30s	remaining: 2m 32s
112:	learn: 0.7888157	total: 7m 33s	remaining: 2m 28s
113:	learn: 0.7880476	total: 7m 37s	remaining: 2m 24s
114:	learn: 0.7873818	total: 7m 42s	remaining: 2m 20s
115:	learn: 0.7864667	total: 7m 45s	remaining: 2m 16s
116:	learn: 0.7857889	total: 7m 49s	remaining: 2m 12s
117:	learn: 0.7848389	total: 7m 53s	remaining: 2m 8s
118:	learn: 0.7840855	total: 7m 58s	remaining: 2m 4s
119:	learn: 0.7833278	total: 8m 1s	remaining: 2m
120:	learn: 0.7827690	total: 8m 5s	remaining: 1m 56s
121:	learn: 0.7822083	total: 8m 10s	remaining: 1m 52s
122:	learn: 0.7817338	total: 8m 13s	remaining: 1m 48s
123:	learn: 0.7809738	total: 8m 17s	remaining: 1m 44s
124:	learn: 0.7804532	total: 8m 21s	remaining: 1m 40s
125:	learn: 0.7799716	total: 8m 26s	remaining: 1m 36s
126:	learn: 0.7795596	total: 8m 29s	remaining: 1m 32s
127:	learn: 0.7790103	total: 8m 33s	remaining: 1m 28s
128:	learn: 0.7782744	total: 8m 38s	remaining: 1m 24s
129:	learn: 0.7776348	total: 8m 42s	remaining: 1m 20s
130:	learn: 0.7768136	total: 8m 45s	remaining: 1m 16s
131:	learn: 0.7764188	total: 8m 49s	remaining: 1m 12s
132:	learn: 0.7758614	total: 8m 54s	remaining: 1m 8s
133:	learn: 0.7754470	total: 8m 57s	remaining: 1m 4s
134:	learn: 0.7746271	total: 9m 1s	remaining: 1m
135:	learn: 0.7742047	total: 9m 6s	remaining: 56.2s
136:	learn: 0.7736559	total: 9m 10s	remaining: 52.2s
137:	learn: 0.7729870	total: 9m 13s	remaining: 48.2s
138:	learn: 0.7725388	total: 9m 17s	remaining: 44.1s
139:	learn: 0.7720667	total: 9m 22s	remaining: 40.2s
140:	learn: 0.7715821	total: 9m 26s	remaining: 36.1s
141:	learn: 0.7709686	total: 9m 29s	remaining: 32.1s
142:	learn: 0.7701139	total: 9m 33s	remaining: 28.1s
143:	learn: 0.7692454	total: 9m 38s	remaining: 24.1s
144:	learn: 0.7685821	total: 9m 41s	remaining: 20.1s
145:	learn: 0.7676780	total: 9m 45s	remaining: 16s
146:	learn: 0.7672193	total: 9m 50s	remaining: 12.1s
147:	learn: 0.7666088	total: 9m 54s	remaining: 8.03s
148:	learn: 0.7661745	total: 9m 57s	remaining: 4.01s
149:	learn: 0.7655098	total: 10m 1s	remaining: 0us

## Predict

In [65]:
# Preparing data in Pool format
dataset_test = Pool(
    data = X_test,
    text_features = [0]
)
predict_classes = model.predict(dataset_test)
predictions = predict_classes

## Create submission

In [66]:
sample_submission = pd.read_csv(os.path.join(path, 'sample_submission.csv'))
sample_submission['rate'] = predictions
sample_submission.head()

   index  rate
0      0     5
1      1     5
2      2     5
3      3     5
4      4     5

In [67]:
sample_submission.to_csv(os.path.join(path, 'submission.csv'), index=False)