<a href="https://colab.research.google.com/github/F1ameX/2025-ODS-NLP/blob/main/practice_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Install and Import Libraries

In [1]:
!pip install --quiet catboost
!pip install --quiet gensim
!pip install --quiet nltk
!pip install --quiet pymystem3

In [2]:
import os
import re
import pandas as pd
import numpy as np

import nltk
from catboost import Pool, CatBoostClassifier
from pymystem3 import Mystem

## Read Data

In [3]:
path = '/content/drive/MyDrive/ods-nlp_src/practice_2/'
train_data = pd.read_csv(os.path.join(path, 'train.csv'))
test_data = pd.read_csv(os.path.join(path, 'test.csv'))
print(f'Number of rows and columns in the train data set: {train_data.shape}')
print(f'Number of rows and columns in the test data set: {test_data.shape}')
train_data.head()

Number of rows and columns in the train data set: (48665, 2)
Number of rows and columns in the test data set: (12167, 2)

   rate                                               text
0     4  Очень понравилось. Были в начале марта  с соба...
1     5  В целом магазин устраивает.\nАссортимент позво...
2     5  Очень хорошо что открылась 5 ка, теперь не над...
3     3  Пятёрочка громко объявила о том как она заботи...
4     3  Тесно, вечная сутолока, между рядами трудно ра...

In [4]:
train_data.groupby('rate').describe()

       text
      count unique                top freq
rate
1      4138   4130             Грязно    3
2      2410   2407  Отстойный магазин    2
3      6126   6070          Нормально    7
4      9922   9763               Норм   14
5     26069  24804    Хороший магазин  107

## Preparing the data and creating Catboost model

In [5]:
train_data['text'].head(15)

0     Очень понравилось. Были в начале марта  с соба...
1     В целом магазин устраивает.\nАссортимент позво...
2     Очень хорошо что открылась 5 ка, теперь не над...
3     Пятёрочка громко объявила о том как она заботи...
4     Тесно, вечная сутолока, между рядами трудно ра...
5     Магазин в пешей доступности. После ремонта и р...
6     Магазин хороший цены и скидки нормальные токо ...
7     Редко сюда забегаю. Маленький магазинчик, но э...
8     Сложно найти в торговом центре. А магазин - норм)
9     После ремонта магазин в нутри стал ещё лучше. ...
10                                Все свежее, продукты.
11    Наша любимая 🤩 \nСделали перестановку, выпечку...
12    Не вызывает этот магазин удовольствие от посещ...
13         Большой выбор продуктов, разнообразные акции
14    Неплохой магазин, но Спар, который там был ран...
Name: text, dtype: object

In [6]:
def process_data(df):
    df['text'] = df['text'].str.lower()
    df['text'] = df['text'].apply(lambda x: re.sub(r'([,.!?;])', r' \1 ', x))
    df['text'] = df['text'].apply(lambda x: re.sub(r'[^\w\s]', '', x))
    df['text'] = df['text'].apply(lambda x: re.sub(r'[\d]', '', x))

    mystem = Mystem()
    df['text'] = df['text'].apply(lambda x: ' '.join(mystem.lemmatize(x)))
    df['text'] = df['text'].apply(lambda x: re.sub(r'[\n]', ' ', x))
    return df

In [7]:
train_data = process_data(train_data)
test_data = process_data(test_data)

In [8]:
train_data.head(15)

    rate                                               text
0      4  очень   понравиться     быть   в   начало   ма...
1      5  в   целое   магазин   устраивать     ассортиме...
2      5  очень   хорошо   что   открываться    ка     т...
3      3  пятерочка   громко   объявлять   о   то   как ...
4      3  тесно     вечный   сутолока     между   ряд   ...
5      4  магазин   в   пеший   доступность     после   ...
6      5  магазин   хороший   цена   и   скидка   нормал...
7      3  редко   сюда   забегать     маленький   магази...
8      5  сложно   находить   в   торговый   центр     а...
9      4  после   ремонт   магазин   в   нутри   станови...
10     5                       все   свежий     продукт
11     5  наш   любимая     сделать   перестановка     в...
12     3  не   вызывать   этот   магазин   удовольствие ...
13     5  большой   выбор   продукт     разнообразный   ...
14     4  неплохой   магазин     но   спар     который  ...

In [10]:
X_train = train_data['text']
y_train = train_data['rate']

X_test = test_data['text']


model = CatBoostClassifier(
    iterations = 250,
    depth = 6,
    random_seed = 52,
)

model.fit(
    X_train,
    y_train,
    verbose=True,
    text_features = [0]
)

Learning rate set to 0.311252
0:	learn: 1.2260014	total: 3.01s	remaining: 12m 28s
1:	learn: 1.1069761	total: 5.1s	remaining: 10m 32s
2:	learn: 1.0418000	total: 6.92s	remaining: 9m 29s
3:	learn: 0.9969966	total: 8.76s	remaining: 8m 58s
4:	learn: 0.9665840	total: 10.4s	remaining: 8m 30s
5:	learn: 0.9490324	total: 12.2s	remaining: 8m 14s
6:	learn: 0.9351377	total: 14.1s	remaining: 8m 8s
7:	learn: 0.9254564	total: 16.6s	remaining: 8m 22s
8:	learn: 0.9171540	total: 18.9s	remaining: 8m 25s
9:	learn: 0.9120253	total: 20.5s	remaining: 8m 10s
10:	learn: 0.9080493	total: 22.1s	remaining: 7m 59s
11:	learn: 0.9029516	total: 23.7s	remaining: 7m 50s
12:	learn: 0.9013978	total: 25.3s	remaining: 7m 40s
13:	learn: 0.8993087	total: 26.8s	remaining: 7m 32s
14:	learn: 0.8971553	total: 28.6s	remaining: 7m 28s
15:	learn: 0.8956294	total: 31.1s	remaining: 7m 35s
16:	learn: 0.8913729	total: 33.4s	remaining: 7m 37s
17:	learn: 0.8899923	total: 34.9s	remaining: 7m 29s
18:	learn: 0.8889738	total: 36.4s	remaining: 7m 22s
19:	learn: 0.8882180	total: 38s	remaining: 7m 16s
20:	learn: 0.8865675	total: 39.6s	remaining: 7m 11s
21:	learn: 0.8856385	total: 41.2s	remaining: 7m 6s
22:	learn: 0.8850006	total: 42.8s	remaining: 7m 2s
23:	learn: 0.8835591	total: 45.3s	remaining: 7m 6s
24:	learn: 0.8827668	total: 47.5s	remaining: 7m 7s
25:	learn: 0.8820285	total: 49.1s	remaining: 7m 2s
26:	learn: 0.8810419	total: 50.6s	remaining: 6m 57s
27:	learn: 0.8803003	total: 52.1s	remaining: 6m 53s
28:	learn: 0.8792202	total: 53.7s	remaining: 6m 49s
29:	learn: 0.8782086	total: 55.4s	remaining: 6m 46s
30:	learn: 0.8774548	total: 57s	remaining: 6m 42s
31:	learn: 0.8770075	total: 59.4s	remaining: 6m 44s
32:	learn: 0.8750985	total: 1m 1s	remaining: 6m 45s
33:	learn: 0.8743062	total: 1m 3s	remaining: 6m 41s
34:	learn: 0.8734741	total: 1m 4s	remaining: 6m 37s
35:	learn: 0.8727830	total: 1m 6s	remaining: 6m 34s
36:	learn: 0.8717229	total: 1m 7s	remaining: 6m 31s
37:	learn: 0.8705464	total: 1m 10s	remaining: 6m 33s
38:	learn: 0.8694170	total: 1m 14s	remaining: 6m 45s
39:	learn: 0.8681521	total: 1m 17s	remaining: 6m 46s
40:	learn: 0.8671659	total: 1m 19s	remaining: 6m 43s
41:	learn: 0.8659530	total: 1m 20s	remaining: 6m 39s
42:	learn: 0.8647632	total: 1m 22s	remaining: 6m 36s
43:	learn: 0.8636346	total: 1m 24s	remaining: 6m 33s
44:	learn: 0.8626653	total: 1m 25s	remaining: 6m 30s
45:	learn: 0.8612376	total: 1m 28s	remaining: 6m 31s
46:	learn: 0.8603916	total: 1m 30s	remaining: 6m 32s
47:	learn: 0.8593954	total: 1m 32s	remaining: 6m 29s
48:	learn: 0.8585696	total: 1m 34s	remaining: 6m 26s
49:	learn: 0.8578364	total: 1m 35s	remaining: 6m 22s
50:	learn: 0.8568310	total: 1m 37s	remaining: 6m 19s
51:	learn: 0.8562588	total: 1m 38s	remaining: 6m 16s
52:	learn: 0.8550527	total: 1m 40s	remaining: 6m 14s
53:	learn: 0.8542723	total: 1m 43s	remaining: 6m 14s
54:	learn: 0.8535987	total: 1m 45s	remaining: 6m 14s
55:	learn: 0.8529263	total: 1m 47s	remaining: 6m 11s
56:	learn: 0.8520073	total: 1m 48s	remaining: 6m 8s
57:	learn: 0.8509512	total: 1m 50s	remaining: 6m 5s
58:	learn: 0.8500240	total: 1m 52s	remaining: 6m 3s
59:	learn: 0.8492667	total: 1m 53s	remaining: 6m
60:	learn: 0.8484449	total: 1m 55s	remaining: 5m 58s
61:	learn: 0.8476972	total: 1m 58s	remaining: 5m 58s
62:	learn: 0.8465052	total: 2m	remaining: 5m 57s
63:	learn: 0.8457855	total: 2m 2s	remaining: 5m 54s
64:	learn: 0.8450311	total: 2m 3s	remaining: 5m 52s
65:	learn: 0.8445019	total: 2m 5s	remaining: 5m 49s
66:	learn: 0.8437981	total: 2m 6s	remaining: 5m 46s
67:	learn: 0.8430125	total: 2m 8s	remaining: 5m 44s
68:	learn: 0.8416856	total: 2m 10s	remaining: 5m 42s
69:	learn: 0.8409190	total: 2m 13s	remaining: 5m 42s
70:	learn: 0.8393308	total: 2m 15s	remaining: 5m 40s
71:	learn: 0.8387768	total: 2m 16s	remaining: 5m 38s
72:	learn: 0.8382035	total: 2m 18s	remaining: 5m 35s
73:	learn: 0.8370551	total: 2m 20s	remaining: 5m 33s
74:	learn: 0.8364962	total: 2m 21s	remaining: 5m 31s
75:	learn: 0.8358716	total: 2m 23s	remaining: 5m 28s
76:	learn: 0.8354640	total: 2m 25s	remaining: 5m 27s
77:	learn: 0.8346344	total: 2m 28s	remaining: 5m 26s
78:	learn: 0.8339722	total: 2m 30s	remaining: 5m 25s
79:	learn: 0.8333271	total: 2m 31s	remaining: 5m 22s
80:	learn: 0.8329283	total: 2m 33s	remaining: 5m 20s
81:	learn: 0.8321639	total: 2m 35s	remaining: 5m 17s
82:	learn: 0.8316254	total: 2m 36s	remaining: 5m 15s
83:	learn: 0.8309468	total: 2m 38s	remaining: 5m 13s
84:	learn: 0.8298128	total: 2m 40s	remaining: 5m 11s
85:	learn: 0.8290808	total: 2m 43s	remaining: 5m 11s
86:	learn: 0.8282529	total: 2m 45s	remaining: 5m 9s
87:	learn: 0.8275983	total: 2m 46s	remaining: 5m 7s
88:	learn: 0.8271283	total: 2m 48s	remaining: 5m 4s
89:	learn: 0.8267816	total: 2m 50s	remaining: 5m 2s
90:	learn: 0.8262286	total: 2m 51s	remaining: 5m
91:	learn: 0.8256001	total: 2m 53s	remaining: 4m 57s
92:	learn: 0.8249332	total: 2m 56s	remaining: 4m 57s
93:	learn: 0.8246116	total: 2m 58s	remaining: 4m 56s
94:	learn: 0.8242952	total: 3m	remaining: 4m 54s
95:	learn: 0.8237878	total: 3m 2s	remaining: 4m 52s
96:	learn: 0.8231820	total: 3m 3s	remaining: 4m 50s
97:	learn: 0.8228351	total: 3m 5s	remaining: 4m 47s
98:	learn: 0.8223439	total: 3m 7s	remaining: 4m 45s
99:	learn: 0.8217586	total: 3m 8s	remaining: 4m 43s
100:	learn: 0.8213943	total: 3m 11s	remaining: 4m 42s
101:	learn: 0.8208935	total: 3m 13s	remaining: 4m 40s
102:	learn: 0.8203410	total: 3m 15s	remaining: 4m 38s
103:	learn: 0.8197553	total: 3m 16s	remaining: 4m 36s
104:	learn: 0.8192949	total: 3m 18s	remaining: 4m 33s
105:	learn: 0.8186853	total: 3m 19s	remaining: 4m 31s
106:	learn: 0.8181491	total: 3m 21s	remaining: 4m 29s
107:	learn: 0.8176212	total: 3m 23s	remaining: 4m 27s
108:	learn: 0.8171147	total: 3m 25s	remaining: 4m 26s
109:	learn: 0.8167224	total: 3m 28s	remaining: 4m 24s
110:	learn: 0.8161134	total: 3m 29s	remaining: 4m 22s
111:	learn: 0.8157157	total: 3m 31s	remaining: 4m 20s
112:	learn: 0.8153788	total: 3m 33s	remaining: 4m 18s
113:	learn: 0.8148268	total: 3m 34s	remaining: 4m 16s
114:	learn: 0.8141961	total: 3m 36s	remaining: 4m 14s
115:	learn: 0.8135880	total: 3m 38s	remaining: 4m 12s
116:	learn: 0.8131579	total: 3m 41s	remaining: 4m 11s
117:	learn: 0.8128184	total: 3m 43s	remaining: 4m 9s
118:	learn: 0.8124752	total: 3m 44s	remaining: 4m 7s
119:	learn: 0.8119262	total: 3m 46s	remaining: 4m 5s
120:	learn: 0.8114804	total: 3m 48s	remaining: 4m 3s
121:	learn: 0.8110609	total: 3m 49s	remaining: 4m 1s
122:	learn: 0.8106418	total: 3m 51s	remaining: 3m 59s
123:	learn: 0.8102735	total: 3m 53s	remaining: 3m 57s
124:	learn: 0.8098649	total: 3m 56s	remaining: 3m 56s
125:	learn: 0.8093624	total: 3m 57s	remaining: 3m 54s
126:	learn: 0.8089133	total: 3m 59s	remaining: 3m 52s
127:	learn: 0.8085580	total: 4m 1s	remaining: 3m 49s
128:	learn: 0.8081312	total: 4m 2s	remaining: 3m 47s
129:	learn: 0.8075463	total: 4m 4s	remaining: 3m 45s
130:	learn: 0.8071532	total: 4m 5s	remaining: 3m 43s
131:	learn: 0.8068670	total: 4m 8s	remaining: 3m 42s
132:	learn: 0.8064706	total: 4m 11s	remaining: 3m 40s
133:	learn: 0.8059896	total: 4m 12s	remaining: 3m 38s
134:	learn: 0.8057412	total: 4m 14s	remaining: 3m 36s
135:	learn: 0.8053027	total: 4m 16s	remaining: 3m 34s
136:	learn: 0.8049962	total: 4m 17s	remaining: 3m 32s
137:	learn: 0.8047068	total: 4m 19s	remaining: 3m 30s
138:	learn: 0.8042899	total: 4m 20s	remaining: 3m 28s
139:	learn: 0.8038574	total: 4m 23s	remaining: 3m 26s
140:	learn: 0.8033729	total: 4m 25s	remaining: 3m 25s
141:	learn: 0.8030197	total: 4m 27s	remaining: 3m 23s
142:	learn: 0.8025139	total: 4m 28s	remaining: 3m 21s
143:	learn: 0.8020409	total: 4m 30s	remaining: 3m 19s
144:	learn: 0.8016929	total: 4m 32s	remaining: 3m 17s
145:	learn: 0.8014686	total: 4m 33s	remaining: 3m 15s
146:	learn: 0.8009578	total: 4m 35s	remaining: 3m 13s
147:	learn: 0.8004652	total: 4m 38s	remaining: 3m 12s
148:	learn: 0.8002052	total: 4m 40s	remaining: 3m 10s
149:	learn: 0.7997819	total: 4m 42s	remaining: 3m 8s
150:	learn: 0.7991079	total: 4m 44s	remaining: 3m 6s
151:	learn: 0.7984728	total: 4m 45s	remaining: 3m 4s
152:	learn: 0.7981579	total: 4m 47s	remaining: 3m 2s
153:	learn: 0.7978035	total: 4m 48s	remaining: 3m
154:	learn: 0.7971541	total: 4m 51s	remaining: 2m 58s
155:	learn: 0.7967735	total: 4m 57s	remaining: 2m 59s
156:	learn: 0.7964913	total: 5m 1s	remaining: 2m 58s
157:	learn: 0.7960066	total: 5m 5s	remaining: 2m 58s
158:	learn: 0.7955116	total: 5m 8s	remaining: 2m 56s
159:	learn: 0.7952563	total: 5m 10s	remaining: 2m 54s
160:	learn: 0.7949199	total: 5m 13s	remaining: 2m 53s
161:	learn: 0.7944965	total: 5m 14s	remaining: 2m 50s
162:	learn: 0.7942543	total: 5m 16s	remaining: 2m 48s
163:	learn: 0.7938716	total: 5m 17s	remaining: 2m 46s
164:	learn: 0.7933958	total: 5m 19s	remaining: 2m 44s
165:	learn: 0.7929700	total: 5m 21s	remaining: 2m 42s
166:	learn: 0.7926364	total: 5m 22s	remaining: 2m 40s
167:	learn: 0.7923487	total: 5m 25s	remaining: 2m 38s
168:	learn: 0.7921054	total: 5m 27s	remaining: 2m 37s
169:	learn: 0.7915091	total: 5m 29s	remaining: 2m 35s
170:	learn: 0.7912343	total: 5m 31s	remaining: 2m 32s
171:	learn: 0.7910390	total: 5m 32s	remaining: 2m 30s
172:	learn: 0.7905992	total: 5m 34s	remaining: 2m 28s
173:	learn: 0.7902748	total: 5m 35s	remaining: 2m 26s
174:	learn: 0.7899764	total: 5m 37s	remaining: 2m 24s
175:	learn: 0.7897590	total: 5m 40s	remaining: 2m 22s
176:	learn: 0.7894282	total: 5m 42s	remaining: 2m 21s
177:	learn: 0.7891940	total: 5m 44s	remaining: 2m 19s
178:	learn: 0.7887641	total: 5m 45s	remaining: 2m 17s
179:	learn: 0.7882857	total: 5m 47s	remaining: 2m 15s
180:	learn: 0.7878822	total: 5m 49s	remaining: 2m 13s
181:	learn: 0.7874696	total: 5m 50s	remaining: 2m 11s
182:	learn: 0.7869238	total: 5m 52s	remaining: 2m 9s
183:	learn: 0.7866801	total: 5m 54s	remaining: 2m 7s
184:	learn: 0.7864162	total: 5m 57s	remaining: 2m 5s
185:	learn: 0.7859680	total: 5m 58s	remaining: 2m 3s
186:	learn: 0.7856047	total: 6m	remaining: 2m 1s
187:	learn: 0.7853278	total: 6m 2s	remaining: 1m 59s
188:	learn: 0.7848686	total: 6m 3s	remaining: 1m 57s
189:	learn: 0.7844877	total: 6m 5s	remaining: 1m 55s
190:	learn: 0.7841213	total: 6m 7s	remaining: 1m 53s
191:	learn: 0.7838810	total: 6m 10s	remaining: 1m 51s
192:	learn: 0.7834456	total: 6m 12s	remaining: 1m 49s
193:	learn: 0.7830083	total: 6m 13s	remaining: 1m 47s
194:	learn: 0.7826315	total: 6m 15s	remaining: 1m 45s
195:	learn: 0.7822811	total: 6m 17s	remaining: 1m 43s
196:	learn: 0.7819739	total: 6m 18s	remaining: 1m 41s
197:	learn: 0.7815635	total: 6m 20s	remaining: 1m 39s
198:	learn: 0.7814103	total: 6m 22s	remaining: 1m 38s
199:	learn: 0.7811489	total: 6m 25s	remaining: 1m 36s
200:	learn: 0.7807923	total: 6m 27s	remaining: 1m 34s
201:	learn: 0.7803078	total: 6m 28s	remaining: 1m 32s
202:	learn: 0.7799332	total: 6m 30s	remaining: 1m 30s
203:	learn: 0.7796748	total: 6m 31s	remaining: 1m 28s
204:	learn: 0.7791937	total: 6m 33s	remaining: 1m 26s
205:	learn: 0.7790218	total: 6m 35s	remaining: 1m 24s
206:	learn: 0.7786843	total: 6m 37s	remaining: 1m 22s
207:	learn: 0.7785111	total: 6m 39s	remaining: 1m 20s
208:	learn: 0.7781728	total: 6m 41s	remaining: 1m 18s
209:	learn: 0.7778833	total: 6m 43s	remaining: 1m 16s
210:	learn: 0.7776296	total: 6m 44s	remaining: 1m 14s
211:	learn: 0.7773819	total: 6m 46s	remaining: 1m 12s
212:	learn: 0.7770982	total: 6m 47s	remaining: 1m 10s
213:	learn: 0.7768271	total: 6m 49s	remaining: 1m 8s
214:	learn: 0.7764830	total: 6m 51s	remaining: 1m 6s
215:	learn: 0.7761007	total: 6m 54s	remaining: 1m 5s
216:	learn: 0.7758084	total: 6m 55s	remaining: 1m 3s
217:	learn: 0.7755151	total: 6m 57s	remaining: 1m 1s
218:	learn: 0.7751546	total: 6m 59s	remaining: 59.4s
219:	learn: 0.7748730	total: 7m	remaining: 57.4s
220:	learn: 0.7743646	total: 7m 2s	remaining: 55.4s
221:	learn: 0.7740396	total: 7m 4s	remaining: 53.5s
222:	learn: 0.7737912	total: 7m 6s	remaining: 51.6s
223:	learn: 0.7733750	total: 7m 8s	remaining: 49.8s
224:	learn: 0.7730755	total: 7m 10s	remaining: 47.9s
225:	learn: 0.7727904	total: 7m 12s	remaining: 45.9s
226:	learn: 0.7725203	total: 7m 13s	remaining: 44s
227:	learn: 0.7722614	total: 7m 15s	remaining: 42s
228:	learn: 0.7719030	total: 7m 16s	remaining: 40.1s
229:	learn: 0.7717394	total: 7m 18s	remaining: 38.1s
230:	learn: 0.7714985	total: 7m 20s	remaining: 36.2s
231:	learn: 0.7711851	total: 7m 23s	remaining: 34.4s
232:	learn: 0.7709147	total: 7m 25s	remaining: 32.5s
233:	learn: 0.7707177	total: 7m 26s	remaining: 30.5s
234:	learn: 0.7705042	total: 7m 28s	remaining: 28.6s
235:	learn: 0.7700176	total: 7m 29s	remaining: 26.7s
236:	learn: 0.7698147	total: 7m 31s	remaining: 24.8s
237:	learn: 0.7695900	total: 7m 33s	remaining: 22.8s
238:	learn: 0.7691651	total: 7m 35s	remaining: 20.9s
239:	learn: 0.7687963	total: 7m 37s	remaining: 19.1s
240:	learn: 0.7686241	total: 7m 39s	remaining: 17.2s
241:	learn: 0.7682570	total: 7m 41s	remaining: 15.2s
242:	learn: 0.7678529	total: 7m 42s	remaining: 13.3s
243:	learn: 0.7674950	total: 7m 44s	remaining: 11.4s
244:	learn: 0.7672073	total: 7m 45s	remaining: 9.51s
245:	learn: 0.7667598	total: 7m 47s	remaining: 7.6s
246:	learn: 0.7665114	total: 7m 49s	remaining: 5.7s
247:	learn: 0.7661761	total: 7m 52s	remaining: 3.81s
248:	learn: 0.7658589	total: 7m 54s	remaining: 1.9s
249:	learn: 0.7654783	total: 7m 55s	remaining: 0us

## Predict

In [11]:
dataset_test = Pool(
    data = X_test,
    text_features = [0]
)

predict_classes = model.predict(dataset_test)
predictions = predict_classes

## Create submission

In [12]:
sample_submission = pd.read_csv(os.path.join(path, 'sample_submission.csv'))
sample_submission['rate'] = predictions
sample_submission.head()

   index  rate
0      0     5
1      1     5
2      2     5
3      3     4
4      4     1

In [13]:
sample_submission.to_csv(os.path.join(path, 'submission.csv'), index=False)