<a href="https://colab.research.google.com/github/F1ameX/2025-ODS-NLP/blob/main/practice_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Install and Import Libraries

In [14]:
!pip install --quiet catboost
!pip install --quiet gensim
!pip install --quiet nltk
!pip install --quiet pymystem3

In [15]:
import os
import re
import pandas as pd
import numpy as np

import nltk
from catboost import Pool, CatBoostClassifier
from pymystem3 import Mystem

## Read Data

In [16]:
path = '/content/drive/MyDrive/ods-nlp_src/practice_2/'
train_data = pd.read_csv(os.path.join(path, 'train.csv'))
test_data = pd.read_csv(os.path.join(path, 'test.csv'))
print(f'Number of rows and columns in the train data set: {train_data.shape}')
print(f'Number of rows and columns in the test data set: {test_data.shape}')
train_data.head()

Number of rows and columns in the train data set: (48665, 2)
Number of rows and columns in the test data set: (12167, 2)

   rate                                               text
0     4  Очень понравилось. Были в начале марта  с соба...
1     5  В целом магазин устраивает.\nАссортимент позво...
2     5  Очень хорошо что открылась 5 ка, теперь не над...
3     3  Пятёрочка громко объявила о том как она заботи...
4     3  Тесно, вечная сутолока, между рядами трудно ра...

In [17]:
train_data.groupby('rate').describe()

       text
      count unique                top freq
rate
1      4138   4130             Грязно    3
2      2410   2407  Отстойный магазин    2
3      6126   6070          Нормально    7
4      9922   9763               Норм   14
5     26069  24804    Хороший магазин  107

## Preparing the data and creating Catboost model

In [18]:
train_data['text'].head(15)

0     Очень понравилось. Были в начале марта  с соба...
1     В целом магазин устраивает.\nАссортимент позво...
2     Очень хорошо что открылась 5 ка, теперь не над...
3     Пятёрочка громко объявила о том как она заботи...
4     Тесно, вечная сутолока, между рядами трудно ра...
5     Магазин в пешей доступности. После ремонта и р...
6     Магазин хороший цены и скидки нормальные токо ...
7     Редко сюда забегаю. Маленький магазинчик, но э...
8     Сложно найти в торговом центре. А магазин - норм)
9     После ремонта магазин в нутри стал ещё лучше. ...
10                                Все свежее, продукты.
11    Наша любимая 🤩 \nСделали перестановку, выпечку...
12    Не вызывает этот магазин удовольствие от посещ...
13         Большой выбор продуктов, разнообразные акции
14    Неплохой магазин, но Спар, который там был ран...
Name: text, dtype: object

In [19]:
def process_data(df):
    df['text'] = df['text'].str.lower()
    df['text'] = df['text'].apply(lambda x: re.sub(r'([,.!?;])', r' \1 ', x))
    df['text'] = df['text'].apply(lambda x: re.sub(r'[^\w\s]', '', x))
    df['text'] = df['text'].apply(lambda x: re.sub(r'[\d]', '', x))

    mystem = Mystem()
    df['text'] = df['text'].apply(lambda x: ' '.join(mystem.lemmatize(x)))
    df['text'] = df['text'].apply(lambda x: re.sub(r'[\n]', ' ', x))
    return df

In [20]:
train_data = process_data(train_data)
test_data = process_data(test_data)

In [21]:
train_data.head(15)

    rate                                               text
0      4  очень   понравиться     быть   в   начало   ма...
1      5  в   целое   магазин   устраивать     ассортиме...
2      5  очень   хорошо   что   открываться    ка     т...
3      3  пятерочка   громко   объявлять   о   то   как ...
4      3  тесно     вечный   сутолока     между   ряд   ...
5      4  магазин   в   пеший   доступность     после   ...
6      5  магазин   хороший   цена   и   скидка   нормал...
7      3  редко   сюда   забегать     маленький   магази...
8      5  сложно   находить   в   торговый   центр     а...
9      4  после   ремонт   магазин   в   нутри   станови...
10     5                       все   свежий     продукт
11     5  наш   любимая     сделать   перестановка     в...
12     3  не   вызывать   этот   магазин   удовольствие ...
13     5  большой   выбор   продукт     разнообразный   ...
14     4  неплохой   магазин     но   спар     который  ...

In [22]:
X_train = train_data['text']
y_train = train_data['rate']

X_test = test_data['text']


model = CatBoostClassifier(
    iterations = 300,
    depth = 7,
    random_seed = 52,
)

model.fit(
    X_train,
    y_train,
    verbose=True,
    text_features = [0]
)

Learning rate set to 0.266811
0:	learn: 1.2669597	total: 3.69s	remaining: 18m 24s
1:	learn: 1.1463925	total: 7.9s	remaining: 19m 37s
2:	learn: 1.0680011	total: 13.6s	remaining: 22m 22s
3:	learn: 1.0207893	total: 17.3s	remaining: 21m 17s
4:	learn: 0.9883720	total: 21s	remaining: 20m 36s
5:	learn: 0.9663706	total: 26.3s	remaining: 21m 29s
6:	learn: 0.9515299	total: 30.4s	remaining: 21m 10s
7:	learn: 0.9381661	total: 34.1s	remaining: 20m 43s
8:	learn: 0.9282570	total: 38.3s	remaining: 20m 39s
9:	learn: 0.9188784	total: 43.6s	remaining: 21m 4s
10:	learn: 0.9131082	total: 47.4s	remaining: 20m 44s
11:	learn: 0.9097962	total: 51s	remaining: 20m 24s
12:	learn: 0.9061952	total: 56.2s	remaining: 20m 40s
13:	learn: 0.9019543	total: 1m	remaining: 20m 35s
14:	learn: 0.8963165	total: 1m 4s	remaining: 20m 21s
15:	learn: 0.8943295	total: 1m 8s	remaining: 20m 9s
16:	learn: 0.8927665	total: 1m 13s	remaining: 20m 24s
17:	learn: 0.8916272	total: 1m 17s	remaining: 20m 10s
18:	learn: 0.8906024	total: 1m 20s	remaining: 19m 56s
19:	learn: 0.8892623	total: 1m 26s	remaining: 20m 4s
20:	learn: 0.8873682	total: 1m 30s	remaining: 19m 58s
21:	learn: 0.8853949	total: 1m 33s	remaining: 19m 44s
22:	learn: 0.8839759	total: 1m 37s	remaining: 19m 31s
23:	learn: 0.8826892	total: 1m 42s	remaining: 19m 40s
24:	learn: 0.8812418	total: 1m 46s	remaining: 19m 28s
25:	learn: 0.8807133	total: 1m 49s	remaining: 19m 16s
26:	learn: 0.8792254	total: 1m 53s	remaining: 19m 12s
27:	learn: 0.8782306	total: 1m 58s	remaining: 19m 12s
28:	learn: 0.8777138	total: 2m 2s	remaining: 19m 1s
29:	learn: 0.8763665	total: 2m 5s	remaining: 18m 51s
30:	learn: 0.8754128	total: 2m 11s	remaining: 18m 56s
31:	learn: 0.8744560	total: 2m 14s	remaining: 18m 47s
32:	learn: 0.8738927	total: 2m 18s	remaining: 18m 37s
33:	learn: 0.8729910	total: 2m 22s	remaining: 18m 31s
34:	learn: 0.8721449	total: 2m 27s	remaining: 18m 34s
35:	learn: 0.8713598	total: 2m 30s	remaining: 18m 25s
36:	learn: 0.8701711	total: 2m 34s	remaining: 18m 17s
37:	learn: 0.8694075	total: 2m 39s	remaining: 18m 16s
38:	learn: 0.8687749	total: 2m 43s	remaining: 18m 12s
39:	learn: 0.8675645	total: 2m 46s	remaining: 18m 4s
40:	learn: 0.8666310	total: 2m 50s	remaining: 17m 56s
41:	learn: 0.8655921	total: 2m 55s	remaining: 17m 59s
42:	learn: 0.8639068	total: 2m 59s	remaining: 17m 51s
43:	learn: 0.8625837	total: 3m 2s	remaining: 17m 44s
44:	learn: 0.8616186	total: 3m 7s	remaining: 17m 40s
45:	learn: 0.8604515	total: 3m 11s	remaining: 17m 39s
46:	learn: 0.8593528	total: 3m 15s	remaining: 17m 32s
47:	learn: 0.8584168	total: 3m 19s	remaining: 17m 24s
48:	learn: 0.8572548	total: 3m 24s	remaining: 17m 25s
49:	learn: 0.8559710	total: 3m 27s	remaining: 17m 19s
50:	learn: 0.8550588	total: 3m 31s	remaining: 17m 12s
51:	learn: 0.8540063	total: 3m 35s	remaining: 17m 6s
52:	learn: 0.8528259	total: 3m 40s	remaining: 17m 7s
53:	learn: 0.8520420	total: 3m 44s	remaining: 17m 1s
54:	learn: 0.8510939	total: 3m 47s	remaining: 16m 54s
55:	learn: 0.8497829	total: 3m 52s	remaining: 16m 52s
56:	learn: 0.8487405	total: 3m 56s	remaining: 16m 48s
57:	learn: 0.8475690	total: 4m	remaining: 16m 42s
58:	learn: 0.8468022	total: 4m 3s	remaining: 16m 35s
59:	learn: 0.8458893	total: 4m 9s	remaining: 16m 36s
60:	learn: 0.8450932	total: 4m 12s	remaining: 16m 30s
61:	learn: 0.8442535	total: 4m 16s	remaining: 16m 23s
62:	learn: 0.8433189	total: 4m 20s	remaining: 16m 20s
63:	learn: 0.8428551	total: 4m 25s	remaining: 16m 17s
64:	learn: 0.8412572	total: 4m 28s	remaining: 16m 11s
65:	learn: 0.8403168	total: 4m 32s	remaining: 16m 5s
66:	learn: 0.8394799	total: 4m 37s	remaining: 16m 5s
67:	learn: 0.8388242	total: 4m 41s	remaining: 15m 59s
68:	learn: 0.8379699	total: 4m 44s	remaining: 15m 53s
69:	learn: 0.8371979	total: 4m 48s	remaining: 15m 48s
70:	learn: 0.8366314	total: 4m 53s	remaining: 15m 46s
71:	learn: 0.8359446	total: 4m 57s	remaining: 15m 41s
72:	learn: 0.8351195	total: 5m	remaining: 15m 35s
73:	learn: 0.8343229	total: 5m 5s	remaining: 15m 32s
74:	learn: 0.8337973	total: 5m 9s	remaining: 15m 28s
75:	learn: 0.8329105	total: 5m 13s	remaining: 15m 23s
76:	learn: 0.8323545	total: 5m 16s	remaining: 15m 17s
77:	learn: 0.8315866	total: 5m 22s	remaining: 15m 17s
78:	learn: 0.8308748	total: 5m 25s	remaining: 15m 11s
79:	learn: 0.8300133	total: 5m 29s	remaining: 15m 5s
80:	learn: 0.8295017	total: 5m 33s	remaining: 15m 1s
81:	learn: 0.8285497	total: 5m 38s	remaining: 14m 59s
82:	learn: 0.8281810	total: 5m 41s	remaining: 14m 53s
83:	learn: 0.8273254	total: 5m 45s	remaining: 14m 48s
84:	learn: 0.8266018	total: 5m 50s	remaining: 14m 46s
85:	learn: 0.8257410	total: 5m 54s	remaining: 14m 41s
86:	learn: 0.8247747	total: 5m 58s	remaining: 14m 36s
87:	learn: 0.8240201	total: 6m 2s	remaining: 14m 32s
88:	learn: 0.8231424	total: 6m 7s	remaining: 14m 30s
89:	learn: 0.8226816	total: 6m 10s	remaining: 14m 25s
90:	learn: 0.8219113	total: 6m 14s	remaining: 14m 20s
91:	learn: 0.8214568	total: 6m 19s	remaining: 14m 18s
92:	learn: 0.8206591	total: 6m 23s	remaining: 14m 14s
93:	learn: 0.8200249	total: 6m 27s	remaining: 14m 9s
94:	learn: 0.8194106	total: 6m 31s	remaining: 14m 4s
95:	learn: 0.8186345	total: 6m 36s	remaining: 14m 3s
96:	learn: 0.8173455	total: 6m 40s	remaining: 13m 58s
97:	learn: 0.8167977	total: 6m 44s	remaining: 13m 53s
98:	learn: 0.8162911	total: 6m 49s	remaining: 13m 51s
99:	learn: 0.8159211	total: 6m 53s	remaining: 13m 47s
100:	learn: 0.8153976	total: 6m 57s	remaining: 13m 42s
101:	learn: 0.8149556	total: 7m 1s	remaining: 13m 37s
102:	learn: 0.8142018	total: 7m 6s	remaining: 13m 36s
103:	learn: 0.8137163	total: 7m 10s	remaining: 13m 31s
104:	learn: 0.8130528	total: 7m 14s	remaining: 13m 26s
105:	learn: 0.8123968	total: 7m 19s	remaining: 13m 24s
106:	learn: 0.8117852	total: 7m 23s	remaining: 13m 19s
107:	learn: 0.8112434	total: 7m 27s	remaining: 13m 15s
108:	learn: 0.8105010	total: 7m 31s	remaining: 13m 10s
109:	learn: 0.8099331	total: 7m 36s	remaining: 13m 8s
110:	learn: 0.8092800	total: 7m 40s	remaining: 13m 3s
111:	learn: 0.8085146	total: 7m 44s	remaining: 12m 58s
112:	learn: 0.8079605	total: 7m 49s	remaining: 12m 56s
113:	learn: 0.8073809	total: 7m 53s	remaining: 12m 52s
114:	learn: 0.8069234	total: 7m 57s	remaining: 12m 47s
115:	learn: 0.8065148	total: 8m	remaining: 12m 42s
116:	learn: 0.8060291	total: 8m 6s	remaining: 12m 40s
117:	learn: 0.8055600	total: 8m 10s	remaining: 12m 35s
118:	learn: 0.8049886	total: 8m 13s	remaining: 12m 31s
119:	learn: 0.8044180	total: 8m 18s	remaining: 12m 28s
120:	learn: 0.8039460	total: 8m 23s	remaining: 12m 24s
121:	learn: 0.8032878	total: 8m 26s	remaining: 12m 19s
122:	learn: 0.8028345	total: 8m 30s	remaining: 12m 15s
123:	learn: 0.8025217	total: 8m 36s	remaining: 12m 12s
124:	learn: 0.8016201	total: 8m 40s	remaining: 12m 8s
125:	learn: 0.8013096	total: 8m 43s	remaining: 12m 3s
126:	learn: 0.8007374	total: 8m 48s	remaining: 11m 59s
127:	learn: 0.8001323	total: 8m 52s	remaining: 11m 55s
128:	learn: 0.7996495	total: 8m 56s	remaining: 11m 51s
129:	learn: 0.7990204	total: 9m	remaining: 11m 46s
130:	learn: 0.7983606	total: 9m 5s	remaining: 11m 44s
131:	learn: 0.7975059	total: 9m 9s	remaining: 11m 39s
132:	learn: 0.7969817	total: 9m 13s	remaining: 11m 34s
133:	learn: 0.7966767	total: 9m 17s	remaining: 11m 30s
134:	learn: 0.7961848	total: 9m 22s	remaining: 11m 27s
135:	learn: 0.7957685	total: 9m 25s	remaining: 11m 22s
136:	learn: 0.7953536	total: 9m 29s	remaining: 11m 17s
137:	learn: 0.7945915	total: 9m 35s	remaining: 11m 15s
138:	learn: 0.7941436	total: 9m 38s	remaining: 11m 10s
139:	learn: 0.7937440	total: 9m 42s	remaining: 11m 5s
140:	learn: 0.7931759	total: 9m 46s	remaining: 11m 1s
141:	learn: 0.7926696	total: 9m 51s	remaining: 10m 58s
142:	learn: 0.7920828	total: 9m 55s	remaining: 10m 53s
143:	learn: 0.7916279	total: 9m 58s	remaining: 10m 48s
144:	learn: 0.7912618	total: 10m 4s	remaining: 10m 46s
145:	learn: 0.7908536	total: 10m 8s	remaining: 10m 41s
146:	learn: 0.7903021	total: 10m 11s	remaining: 10m 36s
147:	learn: 0.7899620	total: 10m 16s	remaining: 10m 32s
148:	learn: 0.7894112	total: 10m 21s	remaining: 10m 29s
149:	learn: 0.7889450	total: 10m 24s	remaining: 10m 24s
150:	learn: 0.7886739	total: 10m 28s	remaining: 10m 20s
151:	learn: 0.7882549	total: 10m 33s	remaining: 10m 17s
152:	learn: 0.7875784	total: 10m 37s	remaining: 10m 12s
153:	learn: 0.7871863	total: 10m 41s	remaining: 10m 8s
154:	learn: 0.7868331	total: 10m 45s	remaining: 10m 4s
155:	learn: 0.7863917	total: 10m 50s	remaining: 10m
156:	learn: 0.7857975	total: 10m 54s	remaining: 9m 55s
157:	learn: 0.7853589	total: 10m 58s	remaining: 9m 51s
158:	learn: 0.7851225	total: 11m 3s	remaining: 9m 48s
159:	learn: 0.7847878	total: 11m 7s	remaining: 9m 43s
160:	learn: 0.7843582	total: 11m 10s	remaining: 9m 39s
161:	learn: 0.7837786	total: 11m 15s	remaining: 9m 35s
162:	learn: 0.7829565	total: 11m 20s	remaining: 9m 31s
163:	learn: 0.7824586	total: 11m 23s	remaining: 9m 27s
164:	learn: 0.7821854	total: 11m 27s	remaining: 9m 22s
165:	learn: 0.7817976	total: 11m 32s	remaining: 9m 18s
166:	learn: 0.7815689	total: 11m 36s	remaining: 9m 14s
167:	learn: 0.7810329	total: 11m 39s	remaining: 9m 9s
168:	learn: 0.7805864	total: 11m 43s	remaining: 9m 5s
169:	learn: 0.7802151	total: 11m 48s	remaining: 9m 1s
170:	learn: 0.7799282	total: 11m 52s	remaining: 8m 57s
171:	learn: 0.7794872	total: 11m 55s	remaining: 8m 52s
172:	learn: 0.7788495	total: 12m	remaining: 8m 48s
173:	learn: 0.7782807	total: 12m 4s	remaining: 8m 44s
174:	learn: 0.7778915	total: 12m 8s	remaining: 8m 40s
175:	learn: 0.7774989	total: 12m 11s	remaining: 8m 35s
176:	learn: 0.7772164	total: 12m 17s	remaining: 8m 32s
177:	learn: 0.7767438	total: 12m 21s	remaining: 8m 27s
178:	learn: 0.7763824	total: 12m 24s	remaining: 8m 23s
179:	learn: 0.7759944	total: 12m 28s	remaining: 8m 19s
180:	learn: 0.7755530	total: 12m 33s	remaining: 8m 15s
181:	learn: 0.7751784	total: 12m 37s	remaining: 8m 10s
182:	learn: 0.7748983	total: 12m 40s	remaining: 8m 6s
183:	learn: 0.7746234	total: 12m 46s	remaining: 8m 3s
184:	learn: 0.7743042	total: 12m 49s	remaining: 7m 58s
185:	learn: 0.7739564	total: 12m 53s	remaining: 7m 54s
186:	learn: 0.7734284	total: 12m 57s	remaining: 7m 49s
187:	learn: 0.7730589	total: 13m 2s	remaining: 7m 46s
188:	learn: 0.7724404	total: 13m 6s	remaining: 7m 41s
189:	learn: 0.7718882	total: 13m 9s	remaining: 7m 37s
190:	learn: 0.7713865	total: 13m 14s	remaining: 7m 33s
191:	learn: 0.7710708	total: 13m 18s	remaining: 7m 29s
192:	learn: 0.7707627	total: 13m 22s	remaining: 7m 24s
193:	learn: 0.7701190	total: 13m 25s	remaining: 7m 20s
194:	learn: 0.7697204	total: 13m 30s	remaining: 7m 16s
195:	learn: 0.7693432	total: 13m 34s	remaining: 7m 12s
196:	learn: 0.7690842	total: 13m 38s	remaining: 7m 7s
197:	learn: 0.7687608	total: 13m 42s	remaining: 7m 3s
198:	learn: 0.7684888	total: 13m 47s	remaining: 6m 59s
199:	learn: 0.7681407	total: 13m 50s	remaining: 6m 55s
200:	learn: 0.7676509	total: 13m 54s	remaining: 6m 50s
201:	learn: 0.7673005	total: 13m 58s	remaining: 6m 47s
202:	learn: 0.7668261	total: 14m 3s	remaining: 6m 42s
203:	learn: 0.7659771	total: 14m 6s	remaining: 6m 38s
204:	learn: 0.7656284	total: 14m 10s	remaining: 6m 34s
205:	learn: 0.7653239	total: 14m 15s	remaining: 6m 30s
206:	learn: 0.7648851	total: 14m 19s	remaining: 6m 26s
207:	learn: 0.7645534	total: 14m 22s	remaining: 6m 21s
208:	learn: 0.7642593	total: 14m 26s	remaining: 6m 17s
209:	learn: 0.7638391	total: 14m 31s	remaining: 6m 13s
210:	learn: 0.7633925	total: 14m 35s	remaining: 6m 9s
211:	learn: 0.7630462	total: 14m 38s	remaining: 6m 4s
212:	learn: 0.7626997	total: 14m 43s	remaining: 6m
213:	learn: 0.7620946	total: 14m 47s	remaining: 5m 56s
214:	learn: 0.7617772	total: 14m 51s	remaining: 5m 52s
215:	learn: 0.7611944	total: 14m 54s	remaining: 5m 47s
216:	learn: 0.7607379	total: 15m	remaining: 5m 44s
217:	learn: 0.7603432	total: 15m 3s	remaining: 5m 39s
218:	learn: 0.7599314	total: 15m 7s	remaining: 5m 35s
219:	learn: 0.7595164	total: 15m 11s	remaining: 5m 31s
220:	learn: 0.7592075	total: 15m 16s	remaining: 5m 27s
221:	learn: 0.7590069	total: 15m 19s	remaining: 5m 23s
222:	learn: 0.7587427	total: 15m 23s	remaining: 5m 18s
223:	learn: 0.7584329	total: 15m 28s	remaining: 5m 14s
224:	learn: 0.7579188	total: 15m 31s	remaining: 5m 10s
225:	learn: 0.7573612	total: 15m 35s	remaining: 5m 6s
226:	learn: 0.7570401	total: 15m 39s	remaining: 5m 2s
227:	learn: 0.7568130	total: 15m 44s	remaining: 4m 58s
228:	learn: 0.7564403	total: 15m 48s	remaining: 4m 53s
229:	learn: 0.7560638	total: 15m 51s	remaining: 4m 49s
230:	learn: 0.7558088	total: 15m 56s	remaining: 4m 45s
231:	learn: 0.7555471	total: 16m	remaining: 4m 41s
232:	learn: 0.7552218	total: 16m 4s	remaining: 4m 37s
233:	learn: 0.7549488	total: 16m 7s	remaining: 4m 32s
234:	learn: 0.7546028	total: 16m 12s	remaining: 4m 29s
235:	learn: 0.7542222	total: 16m 16s	remaining: 4m 24s
236:	learn: 0.7538908	total: 16m 20s	remaining: 4m 20s
237:	learn: 0.7536425	total: 16m 23s	remaining: 4m 16s
238:	learn: 0.7533658	total: 16m 28s	remaining: 4m 12s
239:	learn: 0.7527980	total: 16m 32s	remaining: 4m 8s
240:	learn: 0.7525617	total: 16m 36s	remaining: 4m 3s
241:	learn: 0.7522141	total: 16m 40s	remaining: 3m 59s
242:	learn: 0.7519438	total: 16m 44s	remaining: 3m 55s
243:	learn: 0.7514943	total: 16m 48s	remaining: 3m 51s
244:	learn: 0.7510899	total: 16m 52s	remaining: 3m 47s
245:	learn: 0.7507086	total: 16m 57s	remaining: 3m 43s
246:	learn: 0.7503192	total: 17m	remaining: 3m 39s
247:	learn: 0.7499312	total: 17m 4s	remaining: 3m 34s
248:	learn: 0.7496776	total: 17m 8s	remaining: 3m 30s
249:	learn: 0.7492233	total: 17m 13s	remaining: 3m 26s
250:	learn: 0.7486983	total: 17m 17s	remaining: 3m 22s
251:	learn: 0.7484304	total: 17m 20s	remaining: 3m 18s
252:	learn: 0.7480557	total: 17m 25s	remaining: 3m 14s
253:	learn: 0.7477892	total: 17m 29s	remaining: 3m 10s
254:	learn: 0.7474180	total: 17m 33s	remaining: 3m 5s
255:	learn: 0.7469238	total: 17m 36s	remaining: 3m 1s
256:	learn: 0.7464537	total: 17m 42s	remaining: 2m 57s
257:	learn: 0.7462399	total: 17m 45s	remaining: 2m 53s
258:	learn: 0.7458149	total: 17m 49s	remaining: 2m 49s
259:	learn: 0.7456048	total: 17m 53s	remaining: 2m 45s
260:	learn: 0.7452063	total: 17m 58s	remaining: 2m 41s
261:	learn: 0.7449195	total: 18m 1s	remaining: 2m 36s
262:	learn: 0.7443177	total: 18m 5s	remaining: 2m 32s
263:	learn: 0.7435832	total: 18m 10s	remaining: 2m 28s
264:	learn: 0.7432522	total: 18m 14s	remaining: 2m 24s
265:	learn: 0.7429973	total: 18m 18s	remaining: 2m 20s
266:	learn: 0.7425782	total: 18m 22s	remaining: 2m 16s
267:	learn: 0.7422281	total: 18m 27s	remaining: 2m 12s
268:	learn: 0.7419675	total: 18m 30s	remaining: 2m 8s
269:	learn: 0.7417107	total: 18m 34s	remaining: 2m 3s
270:	learn: 0.7413626	total: 18m 38s	remaining: 1m 59s
271:	learn: 0.7408899	total: 18m 43s	remaining: 1m 55s
272:	learn: 0.7406588	total: 18m 46s	remaining: 1m 51s
273:	learn: 0.7403201	total: 18m 50s	remaining: 1m 47s
274:	learn: 0.7398944	total: 18m 55s	remaining: 1m 43s
275:	learn: 0.7395866	total: 18m 59s	remaining: 1m 39s
276:	learn: 0.7391284	total: 19m 2s	remaining: 1m 34s
277:	learn: 0.7388126	total: 19m 7s	remaining: 1m 30s
278:	learn: 0.7385263	total: 19m 11s	remaining: 1m 26s
279:	learn: 0.7379114	total: 19m 15s	remaining: 1m 22s
280:	learn: 0.7374958	total: 19m 19s	remaining: 1m 18s
281:	learn: 0.7371485	total: 19m 24s	remaining: 1m 14s
282:	learn: 0.7367943	total: 19m 28s	remaining: 1m 10s
283:	learn: 0.7364566	total: 19m 31s	remaining: 1m 6s
284:	learn: 0.7360109	total: 19m 35s	remaining: 1m 1s
285:	learn: 0.7356925	total: 19m 40s	remaining: 57.8s
286:	learn: 0.7353410	total: 19m 44s	remaining: 53.6s
287:	learn: 0.7351619	total: 19m 47s	remaining: 49.5s
288:	learn: 0.7346665	total: 19m 52s	remaining: 45.4s
289:	learn: 0.7342812	total: 19m 56s	remaining: 41.3s
290:	learn: 0.7339477	total: 20m	remaining: 37.1s
291:	learn: 0.7336765	total: 20m 3s	remaining: 33s
292:	learn: 0.7333807	total: 20m 9s	remaining: 28.9s
293:	learn: 0.7330567	total: 20m 12s	remaining: 24.8s
294:	learn: 0.7327431	total: 20m 16s	remaining: 20.6s
295:	learn: 0.7325439	total: 20m 21s	remaining: 16.5s
296:	learn: 0.7323888	total: 20m 25s	remaining: 12.4s
297:	learn: 0.7321087	total: 20m 29s	remaining: 8.25s
298:	learn: 0.7318617	total: 20m 32s	remaining: 4.12s
299:	learn: 0.7314544	total: 20m 37s	remaining: 0us

## Predict

In [23]:
dataset_test = Pool(
    data = X_test,
    text_features = [0]
)

predict_classes = model.predict(dataset_test)
predictions = predict_classes

## Create submission

In [24]:
sample_submission = pd.read_csv(os.path.join(path, 'sample_submission.csv'))
sample_submission['rate'] = predictions
sample_submission.head()

   index  rate
0      0     5
1      1     5
2      2     5
3      3     4
4      4     1

In [25]:
sample_submission.to_csv(os.path.join(path, 'submission.csv'), index=False)