<a href="https://colab.research.google.com/github/F1ameX/2025-ODS-NLP/blob/main/practice_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Install and Import Libraries

In [1]:
!pip install --quiet catboost
!pip install --quiet gensim
!pip install --quiet nltk

In [2]:
import os
import re
import pandas as pd
import numpy as np

import nltk
from catboost import Pool, CatBoostClassifier
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.stem import WordNetLemmatizer

In [3]:
nltk.download('wordnet')
nltk.download('stopwords')
stop_words = set(nltk.corpus.stopwords.words('russian'))

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

## Read Data

In [4]:
path = '/content/drive/MyDrive/ods-nlp_src/practice_2/'
train_data = pd.read_csv(os.path.join(path, 'train.csv'))
test_data = pd.read_csv(os.path.join(path, 'test.csv'))
print(f'Number of rows and columns in the train data set: {train_data.shape}')
print(f'Number of rows and columns in the test data set: {test_data.shape}')
train_data.head()

Number of rows and columns in the train data set: (48665, 2)
Number of rows and columns in the test data set: (12167, 2)

   rate                                               text
0     4  Очень понравилось. Были в начале марта  с соба...
1     5  В целом магазин устраивает.\nАссортимент позво...
2     5  Очень хорошо что открылась 5 ка, теперь не над...
3     3  Пятёрочка громко объявила о том как она заботи...
4     3  Тесно, вечная сутолока, между рядами трудно ра...

In [5]:
train_data.groupby('rate').describe()

       text
      count unique                top freq
rate
1      4138   4130             Грязно    3
2      2410   2407  Отстойный магазин    2
3      6126   6070          Нормально    7
4      9922   9763               Норм   14
5     26069  24804    Хороший магазин  107

## Preparing the data and creating Catboost model

In [6]:
train_data['text'].sample(7)

15346                                     Отличный магазин
36675                  Выбор не большой,но проходить можно
33657    Очень вежливый и отзывчивый персонал работает ...
10585                                Пятерочка без изысков
13501    Всё по новым стандартам Пятëрочек. И приятный ...
44108    Особого ввбора магазинов продуктоввх в том мик...
5269     Персонал хамит, захожу  только в случае крайне...
Name: text, dtype: object

In [7]:
def process_data(df):
    lemmatizer = WordNetLemmatizer()
    df['text'] = df['text'].str.lower()
    df['text'] = df['text'].apply(lambda x: re.sub(r'([,.!?;])', r' \1 ', x))
    df['text'] = df['text'].apply(lambda x: re.sub(r'[^\w\s]', '', x))
    df['text'] = df['text'].apply(lambda x: re.sub(r'[\d]', '', x))
    df['text'] = df['text'].apply(lambda x: ' '.join([lemmatizer.lemmatize(word) for word in x.split()]))

    return df

In [8]:
train_data = process_data(train_data)
test_data = process_data(test_data)

In [9]:
train_data.sample(15)

       rate                                               text
22341     1  ценники всегда не актуальные если скидка на ка...
46895     5  хороший магазин в шаговой доступности большой ...
35043     5  пользуюсь постоянно выбор всегда хороший распо...
26852     1  не понравилось то что днем ранее пришлось долг...
38356     4  пятерочка отличная но аптеку в ней обходите ст...
46733     5                                       без очередей
13536     4  магазин не плохой но очереди большие всегда ин...
35443     5  очень вежливый персонал кассы работают всё нра...
18698     4  приличный магазин чистенько есть всё необходим...
42247     5  отличный ассортимент хорошо оборудован зал не ...
28845     5                ки у вовочки а качество в пятёрочке
22483     3                                  неудобный магазин
24711     3  на некоторые товары необоснованно дорогая цена...
11412     4  моя петерочка буквально под моими окнами сейча...
31461     5  удобно что есть кассы самообслуживания практич...

In [10]:
X_train = train_data['text']
y_train = train_data['rate']

X_test = test_data['text']


model = CatBoostClassifier(
    iterations = 150,
    depth = 5,
    random_seed = 52,
)

model.fit(
    X_train,
    y_train,
    text_features = [0],
    verbose=True
)

Learning rate set to 0.479263
0:	learn: 1.1045265	total: 1.39s	remaining: 3m 27s
1:	learn: 1.0136408	total: 2.95s	remaining: 3m 38s
2:	learn: 0.9674237	total: 4.76s	remaining: 3m 53s
3:	learn: 0.9394648	total: 6.55s	remaining: 3m 59s
4:	learn: 0.9283808	total: 8.5s	remaining: 4m 6s
5:	learn: 0.9200120	total: 9.54s	remaining: 3m 49s
6:	learn: 0.9157135	total: 10.6s	remaining: 3m 35s
7:	learn: 0.9136866	total: 11.6s	remaining: 3m 25s
8:	learn: 0.9090013	total: 12.7s	remaining: 3m 18s
9:	learn: 0.9070450	total: 13.7s	remaining: 3m 11s
10:	learn: 0.9033949	total: 14.8s	remaining: 3m 6s
11:	learn: 0.8989732	total: 15.9s	remaining: 3m 2s
12:	learn: 0.8977457	total: 16.9s	remaining: 2m 58s
13:	learn: 0.8951320	total: 18.2s	remaining: 2m 56s
14:	learn: 0.8944480	total: 19.8s	remaining: 2m 58s
15:	learn: 0.8932566	total: 21.4s	remaining: 2m 59s
16:	learn: 0.8920883	total: 22.9s	remaining: 2m 58s
17:	learn: 0.8907625	total: 23.9s	remaining: 2m 55s
18:	learn: 0.8893843	total: 24.9s	remaining: 2m 51s
19:	learn: 0.8880459	total: 25.9s	remaining: 2m 48s
20:	learn: 0.8870573	total: 26.9s	remaining: 2m 45s
21:	learn: 0.8856918	total: 27.9s	remaining: 2m 42s
22:	learn: 0.8845546	total: 28.9s	remaining: 2m 39s
23:	learn: 0.8802407	total: 30.1s	remaining: 2m 37s
24:	learn: 0.8795700	total: 31s	remaining: 2m 35s
25:	learn: 0.8778338	total: 32.1s	remaining: 2m 33s
26:	learn: 0.8760530	total: 33.5s	remaining: 2m 32s
27:	learn: 0.8748432	total: 35.1s	remaining: 2m 32s
28:	learn: 0.8736624	total: 36.7s	remaining: 2m 33s
29:	learn: 0.8720604	total: 38.2s	remaining: 2m 32s
30:	learn: 0.8707709	total: 39.3s	remaining: 2m 30s
31:	learn: 0.8701285	total: 40.4s	remaining: 2m 28s
32:	learn: 0.8683823	total: 41.4s	remaining: 2m 26s
33:	learn: 0.8676407	total: 42.3s	remaining: 2m 24s
34:	learn: 0.8664101	total: 43.8s	remaining: 2m 23s
35:	learn: 0.8652792	total: 44.9s	remaining: 2m 22s
36:	learn: 0.8645351	total: 46s	remaining: 2m 20s
37:	learn: 0.8634933	total: 47.2s	remaining: 2m 19s
38:	learn: 0.8622522	total: 49s	remaining: 2m 19s
39:	learn: 0.8608531	total: 50.7s	remaining: 2m 19s
40:	learn: 0.8599044	total: 52.6s	remaining: 2m 19s
41:	learn: 0.8591213	total: 53.8s	remaining: 2m 18s
42:	learn: 0.8582883	total: 54.8s	remaining: 2m 16s
43:	learn: 0.8569927	total: 55.8s	remaining: 2m 14s
44:	learn: 0.8560332	total: 56.9s	remaining: 2m 12s
45:	learn: 0.8552473	total: 57.9s	remaining: 2m 10s
46:	learn: 0.8544661	total: 58.9s	remaining: 2m 9s
47:	learn: 0.8533975	total: 60s	remaining: 2m 7s
48:	learn: 0.8526891	total: 1m	remaining: 2m 5s
49:	learn: 0.8518412	total: 1m 1s	remaining: 2m 3s
50:	learn: 0.8511744	total: 1m 3s	remaining: 2m 2s
51:	learn: 0.8505936	total: 1m 4s	remaining: 2m 2s
52:	learn: 0.8498611	total: 1m 6s	remaining: 2m 1s
53:	learn: 0.8491485	total: 1m 7s	remaining: 2m
54:	learn: 0.8484364	total: 1m 8s	remaining: 1m 58s
55:	learn: 0.8471754	total: 1m 9s	remaining: 1m 57s
56:	learn: 0.8460835	total: 1m 11s	remaining: 1m 55s
57:	learn: 0.8455715	total: 1m 12s	remaining: 1m 54s
58:	learn: 0.8444883	total: 1m 13s	remaining: 1m 52s
59:	learn: 0.8438936	total: 1m 14s	remaining: 1m 51s
60:	learn: 0.8433154	total: 1m 15s	remaining: 1m 49s
61:	learn: 0.8428569	total: 1m 16s	remaining: 1m 48s
62:	learn: 0.8424721	total: 1m 17s	remaining: 1m 46s
63:	learn: 0.8418624	total: 1m 18s	remaining: 1m 46s
64:	learn: 0.8412379	total: 1m 20s	remaining: 1m 45s
65:	learn: 0.8406453	total: 1m 22s	remaining: 1m 44s
66:	learn: 0.8401978	total: 1m 23s	remaining: 1m 43s
67:	learn: 0.8397246	total: 1m 24s	remaining: 1m 41s
68:	learn: 0.8387615	total: 1m 25s	remaining: 1m 40s
69:	learn: 0.8384099	total: 1m 26s	remaining: 1m 38s
70:	learn: 0.8376046	total: 1m 27s	remaining: 1m 37s
71:	learn: 0.8371128	total: 1m 28s	remaining: 1m 35s
72:	learn: 0.8367168	total: 1m 29s	remaining: 1m 34s
73:	learn: 0.8362040	total: 1m 30s	remaining: 1m 33s
74:	learn: 0.8355236	total: 1m 31s	remaining: 1m 31s
75:	learn: 0.8350529	total: 1m 33s	remaining: 1m 30s
76:	learn: 0.8343331	total: 1m 35s	remaining: 1m 30s
77:	learn: 0.8340089	total: 1m 37s	remaining: 1m 29s
78:	learn: 0.8335751	total: 1m 38s	remaining: 1m 28s
79:	learn: 0.8333152	total: 1m 39s	remaining: 1m 26s
80:	learn: 0.8327286	total: 1m 40s	remaining: 1m 25s
81:	learn: 0.8321255	total: 1m 41s	remaining: 1m 24s
82:	learn: 0.8314949	total: 1m 42s	remaining: 1m 22s
83:	learn: 0.8308736	total: 1m 43s	remaining: 1m 21s
84:	learn: 0.8298984	total: 1m 44s	remaining: 1m 19s
85:	learn: 0.8292931	total: 1m 45s	remaining: 1m 18s
86:	learn: 0.8286995	total: 1m 46s	remaining: 1m 17s
87:	learn: 0.8282583	total: 1m 47s	remaining: 1m 16s
88:	learn: 0.8273496	total: 1m 49s	remaining: 1m 15s
89:	learn: 0.8267620	total: 1m 51s	remaining: 1m 14s
90:	learn: 0.8262499	total: 1m 52s	remaining: 1m 13s
91:	learn: 0.8256712	total: 1m 53s	remaining: 1m 11s
92:	learn: 0.8253396	total: 1m 54s	remaining: 1m 10s
93:	learn: 0.8249185	total: 1m 55s	remaining: 1m 8s
94:	learn: 0.8243227	total: 1m 56s	remaining: 1m 7s
95:	learn: 0.8240045	total: 1m 57s	remaining: 1m 6s
96:	learn: 0.8236517	total: 1m 58s	remaining: 1m 4s
97:	learn: 0.8232881	total: 1m 59s	remaining: 1m 3s
98:	learn: 0.8227548	total: 2m	remaining: 1m 2s
99:	learn: 0.8223297	total: 2m 1s	remaining: 1m
100:	learn: 0.8217353	total: 2m 2s	remaining: 59.6s
101:	learn: 0.8212902	total: 2m 4s	remaining: 58.7s
102:	learn: 0.8209109	total: 2m 6s	remaining: 57.7s
103:	learn: 0.8205601	total: 2m 7s	remaining: 56.5s
104:	learn: 0.8201869	total: 2m 8s	remaining: 55.2s
105:	learn: 0.8199411	total: 2m 9s	remaining: 53.8s
106:	learn: 0.8196065	total: 2m 10s	remaining: 52.6s
107:	learn: 0.8192432	total: 2m 11s	remaining: 51.3s
108:	learn: 0.8189729	total: 2m 12s	remaining: 50s
109:	learn: 0.8184814	total: 2m 13s	remaining: 48.7s
110:	learn: 0.8179061	total: 2m 14s	remaining: 47.4s
111:	learn: 0.8175299	total: 2m 15s	remaining: 46.1s
112:	learn: 0.8169509	total: 2m 16s	remaining: 44.9s
113:	learn: 0.8164200	total: 2m 18s	remaining: 43.8s
114:	learn: 0.8162154	total: 2m 20s	remaining: 42.8s
115:	learn: 0.8157819	total: 2m 22s	remaining: 41.6s
116:	learn: 0.8153530	total: 2m 23s	remaining: 40.4s
117:	learn: 0.8148974	total: 2m 24s	remaining: 39.1s
118:	learn: 0.8144859	total: 2m 25s	remaining: 37.8s
119:	learn: 0.8140739	total: 2m 26s	remaining: 36.6s
120:	learn: 0.8132896	total: 2m 27s	remaining: 35.3s
121:	learn: 0.8129426	total: 2m 28s	remaining: 34.1s
122:	learn: 0.8124603	total: 2m 29s	remaining: 32.8s
123:	learn: 0.8117100	total: 2m 30s	remaining: 31.6s
124:	learn: 0.8114223	total: 2m 31s	remaining: 30.3s
125:	learn: 0.8110553	total: 2m 33s	remaining: 29.2s
126:	learn: 0.8105450	total: 2m 35s	remaining: 28.1s
127:	learn: 0.8102014	total: 2m 36s	remaining: 27s
128:	learn: 0.8097978	total: 2m 37s	remaining: 25.7s
129:	learn: 0.8094868	total: 2m 38s	remaining: 24.4s
130:	learn: 0.8091577	total: 2m 39s	remaining: 23.2s
131:	learn: 0.8087661	total: 2m 40s	remaining: 21.9s
132:	learn: 0.8083754	total: 2m 41s	remaining: 20.7s
133:	learn: 0.8080751	total: 2m 42s	remaining: 19.4s
134:	learn: 0.8077696	total: 2m 43s	remaining: 18.2s
135:	learn: 0.8073556	total: 2m 44s	remaining: 17s
136:	learn: 0.8069866	total: 2m 45s	remaining: 15.7s
137:	learn: 0.8067714	total: 2m 46s	remaining: 14.5s
138:	learn: 0.8063831	total: 2m 48s	remaining: 13.3s
139:	learn: 0.8061281	total: 2m 49s	remaining: 12.1s
140:	learn: 0.8056717	total: 2m 51s	remaining: 11s
141:	learn: 0.8052055	total: 2m 52s	remaining: 9.74s
142:	learn: 0.8049434	total: 2m 53s	remaining: 8.51s
143:	learn: 0.8045757	total: 2m 54s	remaining: 7.29s
144:	learn: 0.8042940	total: 2m 55s	remaining: 6.07s
145:	learn: 0.8039958	total: 2m 56s	remaining: 4.85s
146:	learn: 0.8036345	total: 2m 57s	remaining: 3.63s
147:	learn: 0.8032644	total: 2m 58s	remaining: 2.42s
148:	learn: 0.8027289	total: 3m	remaining: 1.21s
149:	learn: 0.8024265	total: 3m 1s	remaining: 0us

## Predict

In [11]:
dataset_test = Pool(
    data = X_test,
    text_features = [0]
)

predict_classes = model.predict(dataset_test)
predictions = predict_classes

## Create submission

In [12]:
sample_submission = pd.read_csv(os.path.join(path, 'sample_submission.csv'))
sample_submission['rate'] = predictions
sample_submission.head()

   index  rate
0      0     5
1      1     5
2      2     5
3      3     5
4      4     1

In [13]:
sample_submission.to_csv(os.path.join(path, 'submission.csv'), index=False)